name: Go Tests with Coverage

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - 'main'

jobs:
  unit_tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      # Run all unit tests and generate coverage profile
      #- name: Run HW0 unit tests
      #  run: GLOG=no go test -v -race -coverprofile=hw0_coverage.txt ./peer/tests/HW0/unit

      # name: Run HW0 integration tests
      # run: GLOG=no go test -v -race -coverprofile=coverage.out ./peer/tests/HW0/integration

      #- name: Run HW1 unit tests
      #  run: GLOG=no go test -v -race -coverprofile=hw1_coverage.txt ./peer/tests/HW1/unit

      # name: Run HW1 integration tests
      # run: GLOG=no go test -v -race -coverprofile=coverage.out ./peer/tests/HW1/integration

      # Here we run our tests for Namecoin
      - name: Run Namecoin tests
        run: GLOG=no go test -v -race -coverprofile=namecoin_coverage.txt ./peer/impl/

      # Merge all coverage profiles into a single file
      - name: Merge Coverage Files
        run: |
          echo "mode: set" > coverage.txt
          tail -n +2 namecoin_coverage.txt >> coverage.txt

      # Upload the merged coverage profile as an artifact
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  code_coverage:
    name: "Code Coverage Report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: unit_tests
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is fetched if needed

      - name: Generate Code Coverage Report
        uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
          root-package: github.com/cs438-epfl/2024-proj-namecoin-group-33
